#!/usr/bin/with-contenv bash

case $(uname -m) in
  x86_64)
    ARCH="amd64";
    ;;
  aarch64)
    ARCH="arm64";
    ;;
esac

OMADA_HOME="/app/omada"
LOG_DIR="${OMADA_HOME}/logs"

exec \
    s6-setuidgid abc \
        /usr/bin/jsvc \
            -cwd /app/omada/lib \
            -nodetach \
            -pidfile /config/omada.pid \
            -home /usr/lib/jvm/java-8-openjdk-${ARCH}/jre/ \
            -cp /usr/share/java/commons-daemon.jar:${OMADA_HOME}/lib/*:${OMADA_HOME}/properties \
            -outfile ${LOG_DIR}/startup.log \
            -errfile ${LOG_DIR}/error.log \
            -user abc \
            -procname omada \
            -showversion \
            -server \
            -Xms128m \
            -Xmx1024m \
            -XX:MaxHeapFreeRatio=60 \
            -XX:MinHeapFreeRatio=30  \
            -XX:+HeapDumpOnOutOfMemoryError \
            -XX:HeapDumpPath=${LOG_DIR}/java_heapdump.hprof \
            -Djava.awt.headless=true \
            -Dlog4j2.formatMsgNoLookups=true \
            com.tplink.smb.omada.starter.OmadaLinuxMain