#!/usr/bin/with-contenv bash
# shellcheck shell=bash

#Symlinks
symlinks=( \
/app/omada/data \
/app/omada/properties \
)

shopt -s globstar dotglob

for i in "${symlinks[@]}"; do
    if [[ -d /config/"$(basename "$i")" && ! -L "$i"  ]]; then
        rm -rf "$i"
    fi
    if [[ ! -d /config/"$(basename "$i")" && ! -L "$i"  ]]; then
        mv "$i" /config/
    fi
    if [[ -d /config/"$(basename "$i")" && ! -L "$i"  ]]; then
        ln -s /config/"$(basename "$i")" "$i"
    fi
done

symlinks=( \
/app/omada/logs \
/app/omada/work \
)

for i in "${symlinks[@]}"; do
    if [[ -d /config/"$(basename "$i")" && ! -L "$i"  ]]; then
        rm -rf "$i"
    fi
    if [[ ! -d /config/"$(basename "$i")" && ! -L "$i"  ]]; then
        mkdir -p /config/"$(basename "$i")"
    fi
    if [[ -d /config/"$(basename "$i")" && ! -L "$i"  ]]; then
        ln -s /config/"$(basename "$i")" "$i"
    fi
done

shopt -u globstar dotglob

mkdir -p /app/omada/data/autobackup

#Permissions
lsiown -R abc:abc \
  /config \
  /app
