#!/usr/bin/with-contenv bash

#Symlinks
symlinks=( \
/app/omada/data \
/app/omada/properties \
)

shopt -s globstar dotglob

for i in "${symlinks[@]}"; do
[[ -d /config/"$(basename "$i")" && ! -L "$i"  ]] && rm -rf "$i"
[[ ! -d /config/"$(basename "$i")" && ! -L "$i"  ]] && mv "$i" /config/
[[ -d /config/"$(basename "$i")" && ! -L "$i"  ]] && ln -s /config/"$(basename "$i")" "$i"
done

symlinks=( \
/app/omada/logs \
/app/omada/work \
)

for i in "${symlinks[@]}"; do
[[ -d /config/"$(basename "$i")" && ! -L "$i"  ]] && rm -rf "$i"
[[ ! -d /config/"$(basename "$i")" && ! -L "$i"  ]] && mkdir -p /config/"$(basename "$i")"
[[ -d /config/"$(basename "$i")" && ! -L "$i"  ]] && ln -s /config/"$(basename "$i")" "$i"
done

shopt -u globstar dotglob

mkdir -p /app/omada/data/autobackup

#Permissions
chown -R abc:abc \
  /config \
  /app